### ISSUE TITLE
환경변수 영구 설정 방법

### ISSUE THREAD

**Issue by Hanbyeol-Dev** [Fasoo-OpenProject/OpenOS-DRM#9]
1. "vi /etc/bash.bashrc" 명령어로 실행
2. export LD_LIBRARY_PATH=/usr/local/fasoo 입력 후 저장
3. "source /etc/bash.bashrc" 명령어로 적용

참조 : https://sites.google.com/site/sunitwarehouse/os/linux/0001

**Comment by rasjagal** [comment]
해당 파일 수정해도 적용이 안되서 명령어로 별짓 다했는데 source 명령어를 입력해야 하네요.
echo $LD_LIBRARY_PATH 하면 잘 나옵니다. ㄳㄳ

![image](https://user-images.githubusercontent.com/20657880/92863836-61d5c680-f437-11ea-9fe1-f349f9c7a560.png)
![image](https://user-images.githubusercontent.com/20657880/92863935-80d45880-f437-11ea-95f8-4173b276715c.png)
